baseURL = "http://rubzk.github.io/blog"
languageCode = "en-us"
title = "rubz.dev"
theme = "basic"

# enable for syntax highlighting

pygmentUseClasses = true
pygmentsCodefences = true

[params]
 author = "Tomas Ertola"
 description = "My kind of portafolio"


