baseURL = "http://example.org/"
languageCode = "en-us"
title = "pythom"
theme = "basic"

# enable for syntax highlighting

pygmentUseClasses = true
pygmentsCodefences = true

[params]
 author = "Tomas Ertola"
 description = "My kind of portafolio"


